name: navio_mobile
description: "Navio Mobile App"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_pdfview: ^1.3.1
  path_provider: ^2.1.5
  http: ^1.4.0
  path: ^1.8.3
  provider: ^6.0.5
  file_picker: ^5.5.0
  drift: ^2.26.1
  sqlite3_flutter_libs: ^0.5.32
  shared_preferences: ^2.5.3
  get_it: ^8.0.3
  json_annotation: ^4.9.0
  dio: ^5.8.0+1
  freezed_annotation: ^3.0.0
  html: ^0.15.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  drift_dev: ^2.26.1
  build_runner: ^2.4.15
  freezed: ^3.0.6
  json_serializable: ^6.9.5

flutter:
  uses-material-design: true
